### ISSUE TITLE
'Look up' button does nothing for any project

### ISSUE THREAD

**Issue by randombyte-developer** [jitpack/jitpack.io#2519]
I have tried several projects. After clicking on 'Look up' I have to wait like 2 minutes.

In Chrome this appears:
![bildschirmfoto vom 2018-04-12 14 18 41](https://user-images.githubusercontent.com/10366256/38676880-ba896072-3e5c-11e8-9b06-478f33f2b1b3.png)

In Firefox this:
![bildschirmfoto vom 2018-04-12 14 19 58](https://user-images.githubusercontent.com/10366256/38676891-c3ecc9d8-3e5c-11e8-89f6-61f2a4809aa2.png)

Some project links:
- https://jitpack.io/#randombyte-developer/byte-items
- https://jitpack.io/#rojo8399/PlaceholderAPI
- https://jitpack.io/#randombyte-developer/kosp

**Comment by Steppschuh** [comment]
JitPack seems to be having issues at the moment. Projects depending on it fail to build, for example:

```
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.github.neXenio:BLE-Indoor-Positioning:dev-SNAPSHOT.
Required by:
    project :***********
  at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:103)
  at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:63)
  at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:93)
  ... 42 more
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.github.neXenio:BLE-Indoor-Positioning:dev-SNAPSHOT.
  at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveComponentMetaData(ErrorHandlingModuleComponentRepository.java:129)
  at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ComponentMetaDataResolveState.process(ComponentMetaDataResolveState.java:66)
  at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ComponentMetaDataResolveState.resolve(ComponentMetaDataResolveState.java:58)
  ... 67 more
Caused by: org.gradle.api.resources.ResourceException: Unable to load Maven meta-data from https://jitpack.io/com/github/neXenio/BLE-Indoor-Positioning/dev-SNAPSHOT/maven-metadata.xml.
  at org.gradle.api.internal.artifacts.repositories.resolver.MavenMetadataLoader.load(MavenMetadataLoader.java:55)
  at org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver.parseMavenMetadata(MavenResolver.java:244)
  at org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver.findUniqueSnapshotVersion(MavenResolver.java:223)
  ... 72 more
Caused by: org.gradle.internal.resource.transport.http.HttpRequestException: Could not HEAD 'https://jitpack.io/com/github/neXenio/BLE-Indoor-Positioning/dev-SNAPSHOT/maven-metadata.xml'.
  at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:96)
  at org.gradle.internal.resource.transport.http.HttpClientHelper.performRawHead(HttpClientHelper.java:72)
  at org.gradle.internal.resource.transport.http.HttpClientHelper.performHead(HttpClientHelper.java:76)
  ... 80 more
Caused by: java.net.SocketTimeoutException: Read timed out
```

The stacktrace above just indicates that gradle can't fetch the [Maven meta-data for that dependency](https://jitpack.io/com/github/neXenio/BLE-Indoor-Positioning/dev-SNAPSHOT/maven-metadata.xml) because the request times out.

**Comment by randombyte-developer** [comment]
Works again for me.
