### ISSUE TITLE
Add ability to build and publish Kotlin Multiplatform Libraries

### ISSUE THREAD

**Issue by arkivanov** [jitpack/jitpack.io#3853]
**Is your feature request related to a problem? Please describe.**
We are playing with Kotlin Multiplatform projects at the moment and publishing our artifacts via  JitPack. But JitPack builds only on Linux so we can't build some Native targets (e.g. iOS), as it requires macos host. Taking into account that Github Package Registry is coming, I think it would be nice to add macos host to JitPack.

**Describe the solution you'd like**
Add ability to publish Kotlin Multiplatform libraries with Native targets

**Describe alternatives you've considered**
Manual publishing to JCenter, signed up for Github Package Registry beta

**Additional context**
Travis can be configured to build on multiple hosts, perhaps same technique could be used

**Comment by jitpack-io** [comment]
Hi,

That's an interesting suggestion, thank you!
Would it be enough to build your whole project on macos or do you require some parts built on Linux?

**Comment by arkivanov** [comment]
At the moment we are targeting JVM, iOS and Linux so Macos would work for us as it can build all our targets. But other people might be interested in Windows and it requires Windows host.
So first iteration might be to just allow selection between Linux and Macos (we would just select Macos).
Second iteration might be to allow partial selection.

**Comment by miketrewartha** [comment]
I'll second this. We're investing heavily in Kotlin multi-platform libraries that are published for use on Android and the JVM, but we'll be publishing them for iOS soon, too.

**Comment by jitpack-io** [comment]
Hi,

We've added preliminary support for Kotlin MPP libraries. In particular we now handle Gradle metadata (.module) in our Linux builds.

**Comment by yslvlln** [comment]
Hi, 

Do you have a sample build.gradle for this Kotlin MPP support? I couldn't find any in your existing repositories. 

Thanks!

**Comment by arkivanov** [comment]
@yslvlln Here are some KMP projects: 
https://github.com/badoo/Reaktive - this one uses regular Groovy Gradle scripts
https://github.com/arkivanov/MVIKotlin - this one uses Kotlin Gradle scripts

Hope this helps

**Comment by yslvlln** [comment]
Will look into this. Thanks a lot @arkivanov!

**Comment by jillesvangurp** [comment]
@yslvlln Recently KMP evolved a bit so might be worth another look. Setting this up got a lot easier. Basically the multiplatform plugin has out of the box support for publish. There have been a few changes to the meta data part and how gradle handles this. E.g. It is able to figure out for a js project to depend on the -js variant.

I have a simple project that I'm trying to publish via jitpack currently. Currently it half works in the sense that I can publish  but not depend on the dependencies.

The project is: https://github.com/jillesvangurp/geogeometry & https://jitpack.io/#jillesvangurp/geogeometry

Release 3.1.4 for this was a kotlin multi platform build. See logs + build file in this gist: https://gist.github.com/jillesvangurp/8b1d8bcfa930a0f1a419a11f33462c74

This initially looks like it works. But when I try to depend on the -jvm jar in a different project, I get a 401 from jitpack:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.github.jillesvangurp:geogeometry-jvm:v3.1.4.
     Required by:
         project :
      > Could not resolve com.github.jillesvangurp:geogeometry-jvm:v3.1.4.
         > Could not get resource 'https://jitpack.io/com/github/jillesvangurp/geogeometry-jvm/v3.1.4/geogeometry-jvm-v3.1.4.pom'.
            > Could not GET 'https://jitpack.io/com/github/jillesvangurp/geogeometry-jvm/v3.1.4/geogeometry-jvm-v3.1.4.pom'. Received status code 401 from server: Unauthorized
```

I've also tried depending both:
```
    implementation("com.github.jillesvangurp:geogeometry-jvm:v3.1.4")
```

or 

```
    implementation("com.github.jillesvangurp:geogeometry:v3.1.4")
```

For a different project I use a google storage bucket as a poor man's gradle repository and there it works as it should. So, I know my build file is OK. To me it looks like either files are missing/not uploaded or access to those files is somehow not allowed. Since it seems to be close to working; it might be worth getting this over the finishing line. 

KMP is about to be more important now that Kotlin 1.4 is out so fixing this would be really nice. I have several libraries that are probably going to be multi-platform soon.

**Comment by jillesvangurp** [comment]
Note, for the project above I have now switched to rsyncing a local file repository to my website. This seems to work fine. So the issue is definitely with how jitpack handles the generated artifacts as the exact same artifacts when uploaded unmodified to a website seem to work fine.

**Comment by Hmawn** [comment]
God

**Comment by Hmawn** [comment]
plugins { kotlin("multiplatform") version "1.3.72" id("com.github.ben-manes.versions") version "0.28.0" // gradle dependencyUpdates -Drevision=release id("org.jmailen.kotlinter") version "2.4.1" `maven-publish` } repositories { mavenCentral() maven(url = "https://jitpack.io") } group = "com.github.jillesvangurp" version = "0.1-SNAPSHOT" val kotlinVersion = "1.3.72" val slf4jVersion = "1.7.26" val junitVersion = "5.6.2" kotlin { jvm { val main by compilations.getting { kotlinOptions { // Setup the Kotlin compiler options for the 'main' compilation: jvmTarget = "1.8" } } val test by compilations.getting { kotlinOptions { // Setup the Kotlin compiler options for the 'main' compilation: jvmTarget = "1.8" } } } js { nodejs { } } sourceSets { val commonMain by getting { dependencies { implementation(kotlin("stdlib-common")) } } val commonTest by getting { dependencies { implementation(kotlin("test-common")) implementation(kotlin("test-annotations-common")) // yay kotest does multiplatform implementation("io.kotest:kotest-assertions-core:4.1.3") } } val jvmMain by getting { dependencies { implementation(kotlin("stdlib-jdk8")) } } val jvmTest by getting { dependencies { runtimeOnly("org.junit.jupiter:junit-jupiter:$junitVersion") implementation(kotlin("test-junit")) implementation("org.hamcrest:hamcrest-all:1.3") // kotlintest runner needs this to enable logging implementation("org.slf4j:slf4j-api:$slf4jVersion") implementation("org.slf4j:jcl-over-slf4j:$slf4jVersion") implementation("org.slf4j:log4j-over-slf4j:$slf4jVersion") implementation("org.slf4j:jul-to-slf4j:$slf4jVersion") implementation("ch.qos.logback:logback-classic:1.2.3") implementation("com.google.code.gson:gson:2.8.6") } } val jsMain by getting { dependencies { implementation(kotlin("stdlib-js")) } } val jsTest by getting { dependencies { implementation(kotlin("test-js")) } } } } publishing { repositories { maven { url = uri("file://$buildDir/localRepo") } } } kotlinter { ignoreFailures = true }

**Comment by Zhuinden** [comment]
Hello, is there any news on this? It would be super nice to be able to use Jitpack with KMM projects reliably, especially now that they've officially reached alpha (and hopefully won't make significant changes over time).

**Comment by petersamokhin** [comment]
Hey @jitpack-io, any updates 1.5 years after the creation of this issue? 🙂

**Comment by petersamokhin** [comment]
Hey @jitpack-io, any updates 1.5 years after the creation of this issue? 🙂

**Comment by ligi** [comment]
Would really love to see this @jitpack-io

**Comment by arkivanov** [comment]
Since Jcenter and Bintray are shutting down, it would be really cool to have Jitpack working with Kotlin Multiplatform!

**Comment by ArcticLampyrid** [comment]
@arkivanov 
It's almost available for Kotlin Multiplatform.
For a multi-module project, the artifacts are published under `com.github.USER.REPO:MODULE:VERSION` now.
And version id is provided through project property.

Let's take `https://github.com/ArcticLampyrid/KtJsonRpcPeer` as an example
You can find the following in log
```
Running: ./gradlew clean -Pgroup=com.github.ArcticLampyrid -Pversion=master-9459df002c-1 build publishToMavenLocal
```
We can see that `group` is wrong (it's in a format for single-module project, but KPP is always a multi module project) but `version` is correct.
Then let's overwrite group in build script but keep version as it is.
```kotlin
group = "com.github.ArcticLampyrid.KtJsonRpcPeer"
if (version.toString() == "unspecified") {
    version = "0.7.0" // set if version is not provided (impossible for JitPack)
}
```
Finally kotlin should generate the correct metadata.

**Comment by DetachHead** [comment]
the issue seems to be that for some reason the `publishToLocalMaven` task doesn't output the multiplatform files:

![image](https://user-images.githubusercontent.com/57028336/114071707-c29d8280-98e4-11eb-8289-5c0aaa4eadd0.png)

but the `publish` task does:

![image](https://user-images.githubusercontent.com/57028336/114071925-055f5a80-98e5-11eb-91bd-cdd6960d5276.png)

my solution was to just make the `publish` task output to local maven:
```kts
configure<PublishingExtension> {
    publications {
        // ...
    }
    repositories {
        maven("file://${System.getenv("HOME")}/.m2/repository")
    }
}
```
but that doesn't help because jitpack runs `publishToLocalMaven`, not `publish`. so let's fix that in the `jitpack.yml`:

```yml
install:
  - ./gradlew publish
```

jitpack should now publish all of the necessary files. if anyone is curious [here's the projct](https://github.com/DetachHead/url-builder/tree/jitpack) where i got it (mostly) working

**Comment by ArcticLampyrid** [comment]
@DetachHead `publishToLocalMaven` works fine for me with Kotlin multiplatform libraries

**Comment by DetachHead** [comment]
care to share your config? been tearing my hair out at this for the last few days.

[here's mine](https://github.com/DetachHead/url-builder/blob/jitpack/build.gradle.kts), it's full of dirty hacks because none of it worked out of the box for me.no idea what i'm doing wrong

**Comment by Shabinder** [comment]
**lcurl** missing error when building KMP with **linuxX64** target
https://github.com/jitpack/jitpack.io/issues/4523

**Comment by alexwhb** [comment]
Any progress on this? I'd absolutely love to be able to publish KMM libraries on Github without the headache of a typical maven publish.

**Comment by alexvanyo** [comment]
As of Kotlin 1.6.0, Windows targets can be compiled on any host: https://kotlinlang.org/docs/whatsnew16.html#compilation-of-windows-targets-on-any-host

In particular, that means that if JitPack could be configured to run builds on a macOS host, then that single host should be able to compile all necessary native targets for multiplatform projects with Kotlin 1.6.0 and beyond.

**Comment by theapache64** [comment]
@jitpack-io Any updates? 😇 🤞

**Comment by kierans** [comment]
I'm a little bit surprised this hasn't gotten more attention.

**Comment by ArcticLampyrid** [comment]
Not stale.

**Comment by mariuszmarzec** [comment]
dismissing the objection ☝️

**Comment by stefanhaustein** [comment]
What is blocking this? Is this a resource problem? Would it be feasible to donate to this effort somehow if that helps?

**Comment by ltttttttttttt** [comment]
Does KMP support now? I've been doing this for a long time, But I never did it well

https://github.com/ltttttttttttt/ComposeViews

Prompt when importing:
```
:common:desktopMain: Could not resolve com.github.ltttttttttttt.ComposeViews:compose_views-android:1.3.2.7.test_kmp.
Required by:
    project :common > com.github.ltttttttttttt:ComposeViews:1.3.2.7.test_kmp

:common:commonMain: Could not resolve com.github.ltttttttttttt.ComposeViews:compose_views-android:1.3.2.7.test_kmp.
Required by:
    project :common > com.github.ltttttttttttt:ComposeViews:1.3.2.7.test_kmp
```

Prompt at runtime:
```
Execution failed for task ':common:compileKotlinDesktop'.
> Error while evaluating property 'filteredArgumentsMap' of task ':common:compileKotlinDesktop'
   > Could not resolve all files for configuration ':common:desktopCompileClasspath'.
      > Could not resolve com.github.ltttttttttttt.ComposeViews:compose_views-android:1.3.2.7.test_kmp.
        Required by:
            project :common > com.github.ltttttttttttt:ComposeViews:1.3.2.7.test_kmp
         > No matching variant of com.github.ltttttttttttt.ComposeViews:compose_views-android:1.3.2.7.test_kmp was found. The consumer was configured to find an API of a library, preferably optimized for standard JVMs, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'releaseApiElements-published' capability com.github.ltttttttttttt.ComposeViews:compose_views-android:1.3.2.7.test_kmp declares an API of a library:
                 - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
             - Variant 'releaseRuntimeElements-published' capability com.github.ltttttttttttt.ComposeViews:compose_views-android:1.3.2.7.test_kmp declares a runtime of a library:
                 - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
                 - Other compatible attribute:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
```

**Comment by arkivanov** [comment]
@ltttttttttttt On the first glance, it appears that you compile `common` against `jvm` target. And `common` depends on `com.github.ltttttttttttt.ComposeViews:compose_views-android`, which is only for `android`. `jvm` targets can't have `android` dependencies.

**Comment by arkivanov** [comment]
@ltttttttttttt you should structure your dependencies property. JVM modules can't use Android libraries.

**Comment by ltttttttttttt** [comment]
@arkivanov Thanks, I'll try

**Comment by ltttttttttttt** [comment]
> @ltttttttttttt you should structure your dependencies property. JVM modules can't use Android libraries.

Wow, It's finally ok, Thank you

**Comment by arkivanov** [comment]
Definitely not stale ☝️

**Comment by jillesvangurp** [comment]
It worked for a bit last year and now it's broken again.

This one worked: https://jitpack.io/com/github/jillesvangurp/geogeometry/3.2.24/build.log
This one broke again: https://jitpack.io/com/github/jillesvangurp/geogeometry/3.2.25/build.log

Same with several other projects. Basically the error is that the relevant urls that gradle expects produce 404s. The build is fine, the artifacts are just not getting copied over or end up in the wrong place somehow. Even though the log claims to have found them.

So, I'm going back to deploying releases to a google bucket straight from gradle. I can't depend on Jitpack like this.

**Comment by arkivanov** [comment]
Not stale

**Comment by GuilhE** [comment]
Not stale

**Comment by nathanmeade** [comment]
Does this same issue exist with Maven central or just jitpack?

**Comment by GuilhE** [comment]
Just jitpack

**Comment by Kashif-E** [comment]
do it jitpack

**Comment by dev-lcc** [comment]
any updates?

**Comment by nathanmeade** [comment]
Not stale

**Comment by DenisBronx** [comment]
any progress with this?
the issue was opened more than 4 years ago!

**Comment by nathanmeade** [comment]
At this rate Jitpack is doomed just like jcenter and bintray were lol

**Comment by jeffdgr8** [comment]
Definitely old, but hopefully not stale. 🤞

**Comment by dev-lcc** [comment]
Not stale

**Comment by arkivanov** [comment]
I remember that GitHub Packages requires consumers to have a GitHub token. Whereas normal Maven repositories (including Jitpack) do not. If this is the case, then it sounds like a big blocker.

**Comment by lsafer-meemer** [comment]
`jitpack.io` requires some way of authentication for private repositories too

Or do you mean for public repositories? because I didn't try it for public repositories

`GitHub Packages` has its downsides too:
- the need to add a maven repository for every dependency
- the need to authenticate when publishing
- you cannot just add any random git repository from github as a dependency. you need the author to publish it for you
- requires a lot of configuration to publish something

But when `jitpack.io` just don't work out of the box it or requires
specific configuration or don't work at all.
Other solutions is becoming more reliable while `jitpack.io` is 
becoming more problematic.

**Comment by lsafer-meemer** [comment]
Does `jitpack.io` block the build script from the internet?

It says: 
```
* What went wrong:
Execution failed for task ':kotlinNpmInstall'.
> Process 'Resolving NPM dependencies using yarn' returns 1
```

https://jitpack.io/net/lsafer/enver/da8b1d7cc7/build.log

**Comment by lsafer-meemer** [comment]
Looku at this:

https://stackoverflow.com/questions/74698021/installing-node-lib64-libm-so-6-version-glibc-2-27-not-found-required-by-n

Might be the cause of the error here:
https://jitpack.io/net/lsafer/enver/da8b1d7cc7/build.log

**Comment by lsafer-meemer** [comment]
btw, the link is a failing build for a KMM library I am trying to publish

**Comment by d-costa** [comment]
Yes @arkivanov, GitHub requires an access token even when installing public packages:

> You need an access token to publish, install, and delete private, internal, and public packages.

https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages#authenticating-to-github-packages

This is the reason I started investigating Jitpack, since it is pretty lame to require users to generate a GitHub access token to install packages...

**Comment by amarcolini** [comment]
@lsafer-meemer I had the same problem. The issue is that the Kotlin Multiplatform plugin automatically downloads a local copy of NodeJS and Yarn to build javascript artifacts, but apparently the version it downloads is too new for the operating system Jitpack uses. I fixed it using [this issue](https://youtrack.jetbrains.com/issue/KT-44541). Try adding this to your `build.gradle.kts`:

```kotlin
rootProject.plugins.withType(org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin::class.java) {
    rootProject.the<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension>().nodeVersion = "16.0.0"
}
```

Node version 16.0.0 worked for me.

**Comment by GuilhE** [comment]
Not stale

**Comment by ligi** [comment]
not stale

**Comment by lsafer-meemer** [comment]
> @lsafer-meemer I had the same problem. The issue is that the Kotlin Multiplatform plugin automatically downloads a local copy of NodeJS and Yarn to build javascript artifacts, but apparently the version it downloads is too new for the operating system Jitpack uses. I fixed it using [this issue](https://youtrack.jetbrains.com/issue/KT-44541). Try adding this to your `build.gradle.kts`:
> 
> ```kotlin
> rootProject.plugins.withType(org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin::class.java) {
>     rootProject.the<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension>().nodeVersion = "16.0.0"
> }
> ```
> 
> Node version 16.0.0 worked for me.

Works perfectly. Thanks

**Comment by lsafer-meemer** [comment]
I think its time to close this issue...

Or at least change it to: Upgrade jitpack backend glibc version for compatibility with nodejs version used for kmm projects

**Comment by arkivanov** [comment]
@lsafer-meemer why close? Are we able to publish native targets like iOS, macOS and mingw?

**Comment by lsafer-meemer** [comment]
@arkivanov yes you are right. I was focused on `js` and forgot about other targets.

wow, this is a huge problem. even publishing it manually might be a difficult task.

now I get why people set up github actions for publishing kmm libraries

**Comment by Syrou** [comment]
@jitpack-io Please spend some quality love on this, we are a lot of people who wish to have something easy to upload and share Kotlin Multiplatform libraries with.

**Comment by Skaldebane** [comment]
@jitpack-io Now that KMP is stable this should definitely be addressed as soon as possible.

**Comment by arkivanov** [comment]
Absolutely not stale.

**Comment by Kashif-E** [comment]
not stale

**Comment by ismai117** [comment]
not stale

**Comment by rizmaulana** [comment]
Absolutely not stale.

**Comment by ligi** [comment]
not stale ;-)

**Comment by pmpuro** [comment]
Is it possible to specify MacOS somehow to be used for building?

**Comment by hellomr3** [comment]
any plan to support?

**Comment by theapache64** [comment]
not stale

> yey! this time I got the chance to comment not stale ;)

**Comment by Skaldebane** [comment]
not stale ;)

**Comment by Kashif-E** [comment]
not stale

**Comment by muhammadzkralla** [comment]
Does jitpack now support publishing KMP libraries, or is the issue still open?

**Comment by GuilhE** [comment]
> Does jitpack now support publishing KMP libraries, or is the issue still open?

Not yet, but I hope to live to see that day

**Comment by hellomr3** [comment]
not stale

**Comment by tamimattafi** [comment]
Is there a way to link GitHub actions to jitpack.io? Actions seem to be able to build all KMP targets since they can use a macOS environment, therefore, you don't need to explicitly support them on your servers.

**Comment by kaidotarma** [comment]
Still waiting for a way to use Jitpack to build for iOS native targets, which requires a macOS build environment.
This would be beneficial for not only our own libraries, but also for forked libraries where we want to do some changes.
Hope to see some progress soon. :)

**Comment by aeckar** [comment]
Not stale!

**Comment by yosephws** [comment]
can we expedite this changes? really need it for kmp atm.

**Comment by arkivanov** [comment]
My hunch is that the bottleneck here is hardware changes, not software.

**Comment by Zhuinden** [comment]
The bottleneck is that nobody is looking at this Github issue repository, and the fact the jitpack repositories exist at all is a miracle.

**Comment by yosephws** [comment]
i see, in that case nothing we can do but invest on alternatives, i like jitpack tho, sadly have to let it go for now.

**Comment by nort3x** [comment]
speaking of hosts,
i'm struggling with Kotlin/JS build [here](https://jitpack.io/com/github/Independent-Society-of-Knowledge/MoleKule/a13f0cf6ff/build.log)

```
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/jitpack/.gradle/nodejs/node-v18.0.0-linux-x64/bin/node)
```

it seems like `node` requires a version of libc which is not present in the host
can't i change os and it's version of the builder?

**Comment by amarcolini** [comment]
@nort3x I had this issue myself and commented my solution earlier (I don't blame you for not seeing it). Try changing your node version using [this](https://github.com/jitpack/jitpack.io/issues/3853#issuecomment-1683838845).

**Comment by arkivanov** [comment]
Not stale.

**Comment by arkivanov** [comment]
Never been stale.

**Comment by furkanakcakaya** [comment]
not stale

**Comment by Zhuinden** [comment]
I have a feeling at this point, nobody even knows where and who makes Jitpack run.

I have doubts they even have an actual maintainer.

**Comment by crysxd** [comment]
Sad to see this still being unresolved in 2024

**Comment by ligi** [comment]
not stale - still very much needed!

**Comment by lsafer-meemer** [comment]
5 years later - still needed

**Comment by arkivanov** [comment]
Not stale.

**Comment by freeze-dolphin** [comment]
unable to compile KMP native artifacts, there is an error notifying an out-of-date libstdc++ version:

```
/home/jitpack/.konan/kotlin-native-prebuilt-linux-x86_64-2.1.10/konan/nativelib/11273799383558187795/libllvmstubs.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/jitpack/.konan/kotlin-native-prebuilt-linux-x86_64-2.1.10/konan/nativelib/11273799383558187795/libllvmstubs.so)

java.lang.UnsatisfiedLinkError: /home/jitpack/.konan/kotlin-native-prebuilt-linux-x86_64-2.1.10/konan/nativelib/11273799383558187795/libllvmstubs.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/jitpack/.konan/kotlin-native-prebuilt-linux-x86_64-2.1.10/konan/nativelib/11273799383558187795/libllvmstubs.so)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:767)
	at java.base/java.lang.System.load(System.java:1831)
	at kotlinx.cinterop.JvmUtilsKt.tryLoadKonanLibrary(JvmUtils.kt:182)
	at kotlinx.cinterop.JvmUtilsKt.loadKonanLibrary(JvmUtils.kt:196)
	at llvm.llvm.<clinit>(llvm.kt:7363)
...
```

![Full Log](https://jitpack.io/com/github/freeze-dolphin/aff-compose/kmp-9b1e900150-1/build.log)
![Related Project](https://github.com/freeze-dolphin/aff-compose/blob/9b1e900150aef34ad92509b719e7d325946b4c08/build.gradle.kts)

---

publishing is successful if i remove native build support like ![this](https://github.com/freeze-dolphin/aff-compose/blob/ef9381ce0c4bf1de9d430221163cea98bc8321f1/build.gradle.kts#L62-L82)
```
✅ Build artifacts:
com.github.freeze-dolphin.aff-compose:aff-compose:kmp-ef9381ce0c-1
com.github.freeze-dolphin.aff-compose:aff-compose-jvm:kmp-ef9381ce0c-1

Files: 
com/github/freeze-dolphin/aff-compose/aff-compose/kmp-ef9381ce0c-1
com/github/freeze-dolphin/aff-compose/aff-compose/kmp-ef9381ce0c-1/aff-compose-kmp-ef9381ce0c-1-javadoc.jar
com/github/freeze-dolphin/aff-compose/aff-compose/kmp-ef9381ce0c-1/aff-compose-kmp-ef9381ce0c-1-sources.jar
com/github/freeze-dolphin/aff-compose/aff-compose/kmp-ef9381ce0c-1/aff-compose-kmp-ef9381ce0c-1.jar
com/github/freeze-dolphin/aff-compose/aff-compose/kmp-ef9381ce0c-1/aff-compose-kmp-ef9381ce0c-1.module
com/github/freeze-dolphin/aff-compose/aff-compose/kmp-ef9381ce0c-1/aff-compose-kmp-ef9381ce0c-1.pom
com/github/freeze-dolphin/aff-compose/aff-compose/kmp-ef9381ce0c-1/aff-compose-kmp-ef9381ce0c-1.pom.md5
com/github/freeze-dolphin/aff-compose/aff-compose/kmp-ef9381ce0c-1/aff-compose-kmp-ef9381ce0c-1.pom.sha1

com/github/freeze-dolphin/aff-compose/aff-compose-jvm/kmp-ef9381ce0c-1
com/github/freeze-dolphin/aff-compose/aff-compose-jvm/kmp-ef9381ce0c-1/aff-compose-jvm-kmp-ef9381ce0c-1-javadoc.jar
com/github/freeze-dolphin/aff-compose/aff-compose-jvm/kmp-ef9381ce0c-1/aff-compose-jvm-kmp-ef9381ce0c-1-sources.jar
com/github/freeze-dolphin/aff-compose/aff-compose-jvm/kmp-ef9381ce0c-1/aff-compose-jvm-kmp-ef9381ce0c-1.jar
com/github/freeze-dolphin/aff-compose/aff-compose-jvm/kmp-ef9381ce0c-1/aff-compose-jvm-kmp-ef9381ce0c-1.module
com/github/freeze-dolphin/aff-compose/aff-compose-jvm/kmp-ef9381ce0c-1/aff-compose-jvm-kmp-ef9381ce0c-1.pom
com/github/freeze-dolphin/aff-compose/aff-compose-jvm/kmp-ef9381ce0c-1/aff-compose-jvm-kmp-ef9381ce0c-1.pom.md5
com/github/freeze-dolphin/aff-compose/aff-compose-jvm/kmp-ef9381ce0c-1/aff-compose-jvm-kmp-ef9381ce0c-1.pom.sha1
```

---

maybe time to upgrade the runner system? (similar to #7133 #7189 #7204)

**Comment by StefanOltmann** [comment]
Just learned that JitPack is incompatible with Kotlin Multiplatform by trying it out.
Unfortunate.

In my case I wanted JS and WASM.

**Comment by lsafer-meemer** [comment]
@StefanOltmann JitPack currently supports Jvm/Js/WasmJs Kotlin targets.

**Comment by StefanOltmann** [comment]
That's strange because in my test yesterday it didn't work.
JS & wasmJs targets seemed to be uploaded, but they were somehow broken.

I'm now going again with the classic Maven Central.

**Comment by lsafer-meemer** [comment]
@StefanOltmann maybe something wrong with your config... I already published many projects of mine using JitPack. You may look at the config of this project https://github.com/LSafer/compose-iframe

**Comment by sky130** [comment]
> [@StefanOltmann](https://github.com/StefanOltmann)可能是你的配置有问题……我已经用 JitPack 发布过很多项目了。你可以看看这个项目的配置：https://github.com/LSafer/compose-iframe

here is my jitpack log: https://jitpack.io/com/github/sky130/MiWu/5514659794/build.log
and this is my config: https://github.com/sky130/MiWu/blob/kmp-test/miot-api-kmp-impl/build.gradle.kts

``` log
> Task :kotlinNpmInstall FAILED

/home/jitpack/.gradle/nodejs/node-v24.9.0-linux-x64/bin/node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/jitpack/.gradle/nodejs/node-v24.9.0-linux-x64/bin/node)
/home/jitpack/.gradle/nodejs/node-v24.9.0-linux-x64/bin/node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/jitpack/.gradle/nodejs/node-v24.9.0-linux-x64/bin/node)
/home/jitpack/.gradle/nodejs/node-v24.9.0-linux-x64/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /home/jitpack/.gradle/nodejs/node-v24.9.0-linux-x64/bin/node)
/home/jitpack/.gradle/nodejs/node-v24.9.0-linux-x64/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/jitpack/.gradle/nodejs/node-v24.9.0-linux-x64/bin/node)
/home/jitpack/.gradle/nodejs/node-v24.9.0-linux-x64/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/jitpack/.gradle/nodejs/node-v24.9.0-linux-x64/bin/node)
```

I'm not sure what I need to configure; it might be related to the Kotlin version.

**Comment by lsafer-meemer** [comment]
Kotlin made it more easy to publish something to maven. Six years is enough for JitPack users to wait for this issue to be fixed. Plus, maven is way better than JitPack when it comes to build/publish wait time and accessibility. This is the guide from official Kotlin website:

https://kotlinlang.org/docs/multiplatform/multiplatform-publish-libraries.html

JitPack had one advantage with publishing code with zero publish config. This is no longer the case.

**Comment by lotosbin** [comment]
The storage limitation of maven makes it impossible to use it effectively, which is not a good choice.

**Comment by ShadowRZ** [comment]
@jitpack-io Can you just reply? 45 (likely) people is waiting for your response for the entire KMP world.
