### ISSUE TITLE
CMake not found in SDK, PATH, or by cmake.dir property.

### ISSUE THREAD

**Issue by nikolaypuliaev** [jitpack/jitpack.io#4843]
Hello JItpackers!

- Link to build log from https://jitpack.io: https://jitpack.io/de/kenkou/SDK-Android/3.0-alpha02-dsp-library/build.log
- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?: **Yes**
- What error are you seeing?: `> [CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.`

I have an issue when building project with C++ code. I've found [same issue ](https://github.com/jitpack/jitpack.io/issues/3437), in comments there is a statement that it's required to add CMake version install and I've added it, here's my jitpack.yml:
``` yml
jdk:
  - openjdk11
before_install:
  - yes | sdkmanager "cmake;3.18.1"
  ```
Jitpack tries to install needed CMake but throws an exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

How can I properly install CMake and use it during the build?

**Comment by nikolaypuliaev** [comment]
Answer from Jitpack Support

```
Hi

Thank you for raising the issue. It seems sdkmanager cannot run with Java 11 which is specified in jitpack.yml.
One way around it is to run sdkmanager with Java 8 (default) and the rest of build with Java 11.
Something like:
before_install:
- yes | sdkmanager "cmake;3.18.1"
- sdk install java 11.0.10-open
- sdk use java 11.0.10-open
```
