### ISSUE TITLE
Build issue: Conflict with diffplug/spotless/issues/834

### ISSUE THREAD

**Issue by Afanyiyu** [jitpack/jitpack.io#4942]
- Link to build log from https://jitpack.io

https://jitpack.io/com/ilharper/droidup/dc9dc7c31f/build.log
https://jitpack.io/com/ilharper/droidup/f2d91f73bd/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes

- What error are you seeing?

```
Could not write standard input to Gradle build daemon.
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
```

---

Project: [ifrstr/droidup](https://github.com/ifrstr/droidup)

**Comment by Afanyiyu** [comment]
Err...

Conflict with [diffplug/spotless/issues/834](https://github.com/diffplug/spotless/issues/834)
