### ISSUE TITLE
Build fails with IOException

### ISSUE THREAD

**Issue by residuum** [jitpack/jitpack.io#5063]
Building the Android library fails with

    IO exception while downloading manifest:
        java.io.FileNotFoundException: https://dl.google.com/android/repository/sys-img/android-desktop/sys-img2-3.xml
            at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909)
            at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
            at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
            at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openUrl(DownloadCache.java:246)
            at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.downloadAndCache(DownloadCache.java:622)
            at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openCachedUrl(DownloadCache.java:545)
            at com.android.sdklib.repository.legacy.LegacyDownloader.downloadAndStream(LegacyDownloader.java:65)
            at com.android.repository.impl.downloader.LocalFileAwareDownloader.downloadAndStream(LocalFileAwareDownloader.java:51)
            at com.android.repository.impl.manager.RemoteRepoLoaderImpl.lambda$fetchPackages$0(RemoteRepoLoaderImpl.java:138)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)

On my machine, this builds just fine:

    thomas@Minerva:~/dev/android/common$ ./gradlew clean -Pgroup=com.github.SensorApps -Pversion=d0b3396c95 -xtest -xlint assemble publishToMavenLocal
    (snipping irrelevant output)
    BUILD SUCCESSFUL in 4s
    44 actionable tasks: 37 executed, 7 up-to-date

This is strange, because the offending URL https://dl.google.com/android/repository/sys-img/android-desktop/sys-img2-3.xml returns 404.

The link to the build log: https://jitpack.io/com/github/SensorApps/Common/d0b3396c95/build.log

**Comment by residuum** [comment]
Unsure, if this Stackoverflow question helps with resolving the issue:
https://stackoverflow.com/questions/72048885/sdkmanager-in-cmd-throws-io-exception

**Comment by residuum** [comment]
Seems to be a bug in the Android build tools. https://issuetracker.google.com/issues/229992980

**Comment by residuum** [comment]
Google build tools are fixed
