### ISSUE TITLE
build error of "no ndk version"

### ISSUE THREAD

**Issue by imtianx** [jitpack/jitpack.io#5148]
- build log 
https://jitpack.io/com/github/chainx-org/dogecoin-android-api/v0.1.7/build.log

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode)
Getting tasks: ./gradlew tasks --all
Tasks: publishToMavenLocal,
Running: ./gradlew clean -Pgroup=com.github.chainx-org -Pversion=v0.1.7 -xtest -xlint assemble publishToMavenLocal
Installing NDK 22.1.7171670:
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
> Task :clean UP-TO-DATE
> Task :dogecoin:clean
> Task :dogecoin:preBuild UP-TO-DATE
> Task :dogecoin:preDebugBuild UP-TO-DATE
> Task :dogecoin:mergeDebugJniLibFolders
> Task :dogecoin:compileDebugAidl NO-SOURCE
> Task :dogecoin:mergeDebugNativeLibs
> Task :dogecoin:stripDebugDebugSymbols FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dogecoin:stripDebugDebugSymbols'.
> No version of NDK matched the requested version 22.1.7171670. Versions available locally: 21.1.6352462
```

but using the git comiit hash is success:
https://jitpack.io/com/github/chainx-org/dogecoin-android-api/230252ae18/build.log

**Comment by imtianx** [comment]
#4989
