### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by shivamp2404** [jitpack/jitpack.io#6068]
Please provide:

- Link to build log from https://jitpack.io
```
Preparing "Install Android SDK Platform 28 (revision: 6)".
Warning: An error occurred while preparing SDK package Android SDK Platform 28: No space left on device.:
java.io.IOException: No space left on device
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
	at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)
	at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at com.android.repository.util.InstallerUtil.readZipEntry(InstallerUtil.java:199)
	at com.android.repository.util.InstallerUtil.unzip(InstallerUtil.java:143)
	at com.android.repository.impl.installer.BasicInstaller.doPrepare(BasicInstaller.java:90)
	at com.android.repository.impl.installer.AbstractPackageOperation.prepare(AbstractPackageOperation.java:335)
	at com.android.builder.sdk.DefaultSdkLoader.installRemotePackages(DefaultSdkLoader.java:365)
	at com.android.builder.sdk.DefaultSdkLoader.installTarget(DefaultSdkLoader.java:244)
	at com.android.builder.sdk.DefaultSdkLoader.getTargetInfo(DefaultSdkLoader.java:161)
	at com.android.build.gradle.internal.SdkHandler.initTarget(SdkHandler.java:131)
	at com.android.build.gradle.internal.SdkFullLoadingStrategy.init(SdkFullLoadingStrategy.kt:49)
	at com.android.build.gradle.internal.SdkFullLoadingStrategy.getFileFromTarget(SdkFullLoadingStrategy.kt:64)
	at com.android.build.gradle.internal.SdkFullLoadingStrategy.getAidlFramework(SdkFullLoadingStrategy.kt:65)
	at com.android.build.gradle.internal.SdkLoadingStrategy.getAidlFramework(SdkLoadingStrategy.kt:28)
	at com.android.build.gradle.internal.BuildToolsExecutableInput$aidlFrameworkProvider$1.transform(SdkComponents.kt:502)
	at com.android.build.gradle.internal.BuildToolsExecutableInput$aidlFrameworkProvider$1.transform(SdkComponents.kt:501)
	at org.gradle.api.internal.provider.ValueSupplier$Present.transform(ValueSupplier.java:541)
	at org.gradle.api.internal.provider.TransformBackedProvider.mapValue(TransformBackedProvider.java:91)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:83)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:98)
	at org.gradle.api.internal.provider.ProviderResolutionStrategy$1.resolve(ProviderResolutionStrategy.java:27)
	at org.gradle.api.internal.file.collections.ProviderBackedFileCollection.visitDependencies(ProviderBackedFileCollection.java:57)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:103)
```

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
No

- What error are you seeing?

Warning: An error occurred while preparing SDK package Android SDK Platform 28: No space left on device.:
java.io.IOException: No space left on device

Getting these error more frequently from the past few months during building tag on jitpack, what is the issue here?
Thank you!

**Comment by shivamp2404** [comment]
@jitpack-io can you please help?
