### ISSUE TITLE
Ok2Curl/0.2.4 is being compiled with Java 8

### ISSUE THREAD

**Issue by bryant1410** [jitpack/jitpack.io#637]
I see that 0.2.4 version [is compiled with Java 8](https://jitpack.io/com/github/mrmike/Ok2Curl/0.2.4/build.log) while [0.2.3 doesn't](https://jitpack.io/com/github/mrmike/Ok2Curl/0.2.3/build.log). This breaks my Android build:

```
:app:transformClassesWithDexForProductionDebug
Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
    UNEXPECTED TOP-LEVEL EXCEPTION:
    java.lang.RuntimeException: Exception parsing classes
        at com.android.dx.command.dexer.Main.processClass(Main.java:761)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:727)
        at com.android.dx.command.dexer.Main.access$1200(Main.java:87)
        at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1655)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:681)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:578)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:315)
        at com.android.dx.command.dexer.Main.run(Main.java:286)
        at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:52)
        at com.android.builder.core.AndroidBuilder$2.call(AndroidBuilder.java:1511)
        at com.android.builder.core.AndroidBuilder$2.call(AndroidBuilder.java:1507)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
        at com.android.dx.command.dexer.Main.parseClass(Main.java:773)
        at com.android.dx.command.dexer.Main.access$1600(Main.java:87)
        at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1694)
        at com.android.dx.command.dexer.Main.processClass(Main.java:758)
        ... 17 more
```

I also tried a clean build. This doesn't seem to be a library issue, as the only change is upgrading OkHttp dependency to a version I already have.

**Comment by jitpack-io** [comment]
Hi,

You're right, it was build with java 8 which is now the default. 
You could use the jitpack.yml file to specify java version 7.

**Comment by bryant1410** [comment]
But won't using java 8 by default break all android libraries?

**Comment by bryant1410** [comment]
Maybe you can use java 6 by default if it's an android library with minSdkVersion < 19 an java 7 if it's an android library with minSdkVersion < 23. Unless stated in a jitpack.yml file.

**Comment by jitpack-io** [comment]
@bryant1410 Good idea! Let's see what we can do...

**Comment by jitpack-io** [comment]
How is Ok2Curl 0.2.5 for you? Saw that it's now has target compatibility set to java 7.

**Comment by bryant1410** [comment]
Yeah, I see. It works. Seems like they noticed users started having problems. But I think you people should do what's written above. It shouldn't be necessary to set compatibility properties in order to work with JitPack.
