### ISSUE TITLE
ProcessException with JakeWharton/ViewPagerIndicator

### ISSUE THREAD

**Issue by AlmogBaku** [jitpack/jitpack.io#81]
With android studio's gradle structure:
**`project/build.gradle`**:
```
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://jitpack.io"
        }
    }
}
```

**`project/app/build.gradle`**:
```
dependencies {
    // Libs
    compile fileTree(dir: 'libs', include: ['*.jar'])

    // dependencies
    compile 'com.android.support:appcompat-v7:22.1.1'
    compile 'com.github.JakeWharton:ViewPagerIndicator:2.4.1@aar'
}
```

Error:
```
:app:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2
Information:BUILD FAILED
```

**Comment by jitpack-io** [comment]
Hi! 
Can't seem to reproduce this issue. Do you still get the exception?

**Comment by jitpack-io** [comment]
Closing due to inactivity
