### ISSUE TITLE
Oxygen OS (MM) SystemUI.apk recompile error.

### ISSUE THREAD

**Issue by avi-vish** [jitpack/jitpack.io#933]

**Comment by avi-vish** [comment]
Hi.. I'm trying to make a few changes to my SystemUI.apk (Oxygen OS 3.2.7, Marshmallow 6.0.1).  The framework-res.apk decompiles and recompiles just fine . The SystemUI.apk decompiles but throws the following error during recompiling .. 

C:\apktool>apktool -c b SystemUI
I: Using Apktool 2.2.1
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'drag_to_add_tiles' has no default translation.
W: warning: string 'keyguard_plugged_in_dash_charging' has no default translation.
W: warning: string 'notification_content_disable_button' has no default translation.
W: warning: string 'notification_content_disable_button_in_nav' has no default translation.
W: warning: string 'notification_title_disable_button' has no default translation.
W: warning: string 'notifications_off_text' has no default translation.
W: warning: string 'notifications_off_title' has no default translation.
W: warning: string 'qs_edit' has no default translation.
W: warning: string 'quick_settings_buttons_label' has no default translation.
W: warning: string 'volume_footer_no_disturb' has no default translation.
W: warning: string 'volume_footer_ring' has no default translation.
W: warning: string 'volume_footer_slient' has no default translation.


W: C:\apktool\SystemUI\res\values-fa\plurals.xml:8: error: Multiple substitutions
    specified in non-positional format; did you mean to add the formatted="false"
      attribute?
W:
W: C:\apktool\SystemUI\res\values-fa\plurals.xml:8: error: Found tag </item> where </plurals> is expected
W:
W: C:\apktool\SystemUI\res\values-th\plurals.xml:8: error: Multiple substitutions 
	specified in non-positional format; did you mean to add the formatted="false"
	  attribute?
W:
W: C:\apktool\SystemUI\res\values-th\plurals.xml:8: error: Found tag </item> where </plurals> is expected
W: Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.
	AndrolibException: brut.common.BrutException: could not exec (exit code = 1  ): [C:\Users\
	  Avinash\AppData\Local\Temp\brut_util_Jar_4013670714821373130.tmp, p,
		--forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 23, --version-code,
			23, --version-name, 6.0.1, -F, C:\Users\Avinash\AppData\Local\Temp\APKTOOL4914359995357466782.tmp, -0, arsc, -0, arsc, -I, C:\Users\Avinash\AppData\Local\apktool\framework\1.apk, -S, C:\apktool\SystemUI\res, -M, C:\apktool\SystemUI\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
        at brut.androlib.Androlib.buildResources(Androlib.java:412)
        at brut.androlib.Androlib.build(Androlib.java:311)
        at brut.androlib.Androlib.build(Androlib.java:264)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
		
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
    exec (exit code = 1): [C:\Users\Avinash\AppData\Local\Temp\brut_util_Jar_4013670714821373130.tmp,
	   p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 23, --version-code, 23, --version-name, 6.0.1, -F,
    	 C:\Users\Avinash\AppData\Local\Temp\APKTOOL4914359995357466782.tmp, -0, arsc, -0, arsc, -I,
 		   C:\Users\Avinash\AppData\Local\apktool\framework\1.apk, -S, C:\apktool\SystemUI\res,-M, 
		      C:\apktool\SystemUI\AndroidManifest.xml] 
	    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
        ... 5 more
		
 Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Avinash\AppData\Local\Temp\brut_util_Jar_4013670714821373130.tmp,
      p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 23, --version-code,23, --version-name, 6.0.1, -F, C:\Users\Avinash\AppData\Local\Temp\APKTOOL4914359995357466782.tmp, -0, arsc, -0, arsc, -I, C:\Users\Avinash\AppData\Local\apktool\framework\1.apk,-S, C:\apktool\SystemUI\res, -M, C:\apktool\SystemUI\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
        ... 6 more

Can you please tell me what the issue is ? Thanks...
